List<String> myCategories = [
  'General Knowledge',
  'Books',
  'Film',
  'Music',
  'Musical & Theatres',
  'TV',
  'Video Games',
  'Board Games',
  'Science & Nature',
  'Computers',
  'Mathematics',
  'Mythology',
  'Sports',
  'Geography',
  'History',
  'Politics',
  'Art',
  'Celebrities',
  'Animals',
  'Vehicles',
  'Comics',
  'Gadgets',
  'Anime & Manga',
  'Cartoon & Animations',
];

const int categoryOffset = 9;
