// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlnWgp2J73gesotXA8H3csgJHZURcw5jo',
    appId: '1:1091933963597:web:817403e80deac536d72304',
    messagingSenderId: '1091933963597',
    projectId: 'frases-argentinas-dev',
    authDomain: 'frases-argentinas-dev.firebaseapp.com',
    storageBucket: 'frases-argentinas-dev.appspot.com',
    measurementId: 'G-BHZX5WTQ71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgV_TjXq-OsvzvlHTMAcEpgYuIUZ0CK4',
    appId: '1:1091933963597:android:d42e712c5d52d16dd72304',
    messagingSenderId: '1091933963597',
    projectId: 'frases-argentinas-dev',
    storageBucket: 'frases-argentinas-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtPf62uscRu10E163ecE3YbHKaOfOXlg',
    appId: '1:1091933963597:ios:7827c424269d54d6d72304',
    messagingSenderId: '1091933963597',
    projectId: 'frases-argentinas-dev',
    storageBucket: 'frases-argentinas-dev.appspot.com',
    iosClientId: '1091933963597-icqej3p73nmn2rub0t4766s4iqt6hbvf.apps.googleusercontent.com',
    iosBundleId: 'com.wikispiders.frases.argentinas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwtPf62uscRu10E163ecE3YbHKaOfOXlg',
    appId: '1:1091933963597:ios:0b3f6be629e33d92d72304',
    messagingSenderId: '1091933963597',
    projectId: 'frases-argentinas-dev',
    storageBucket: 'frases-argentinas-dev.appspot.com',
    iosClientId: '1091933963597-pepn496o8pt2qtavqchgg77835ub4597.apps.googleusercontent.com',
    iosBundleId: 'com.wikispiders.frases.argentinas.RunnerTests',
  );
}
